/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Helper Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mapping.mapping.HelperStatement#getStatement <em>Statement</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.HelperStatement#getChildRules <em>Child Rules</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.HelperStatement#getChildHelpers <em>Child Helpers</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mapping.mapping.MappingPackage#getHelperStatement()
 * @model
 * @generated
 */
public interface HelperStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Statement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' attribute.
   * @see #setStatement(String)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getHelperStatement_Statement()
   * @model
   * @generated
   */
  String getStatement();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.HelperStatement#getStatement <em>Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement</em>' attribute.
   * @see #getStatement()
   * @generated
   */
  void setStatement(String value);

  /**
   * Returns the value of the '<em><b>Child Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mapping.mapping.MappingRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child Rules</em>' containment reference list.
   * @see org.xtext.example.mapping.mapping.MappingPackage#getHelperStatement_ChildRules()
   * @model containment="true"
   * @generated
   */
  EList<MappingRule> getChildRules();

  /**
   * Returns the value of the '<em><b>Child Helpers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mapping.mapping.HelperStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child Helpers</em>' containment reference list.
   * @see org.xtext.example.mapping.mapping.MappingPackage#getHelperStatement_ChildHelpers()
   * @model containment="true"
   * @generated
   */
  EList<HelperStatement> getChildHelpers();

} // HelperStatement
