/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EEnumLiteral;
import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getSource <em>Source</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getEEnumLiteral <em>EEnum Literal</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getTarget <em>Target</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getComment <em>Comment</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getChildRules <em>Child Rules</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingRule#getChildHelpers <em>Child Helpers</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule()
 * @model
 * @generated
 */
public interface MappingRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(VariableDeclaration)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Var()
   * @model containment="true"
   * @generated
   */
  VariableDeclaration getVar();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(VariableDeclaration value);

  /**
   * Returns the value of the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier</em>' attribute.
   * @see #setIdentifier(String)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Identifier()
   * @model
   * @generated
   */
  String getIdentifier();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getIdentifier <em>Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier</em>' attribute.
   * @see #getIdentifier()
   * @generated
   */
  void setIdentifier(String value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(EObject)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Source()
   * @model
   * @generated
   */
  EObject getSource();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(EObject value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(VariableDeclaration)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Variable()
   * @model
   * @generated
   */
  VariableDeclaration getVariable();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(VariableDeclaration value);

  /**
   * Returns the value of the '<em><b>EEnum Literal</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>EEnum Literal</em>' reference.
   * @see #setEEnumLiteral(EEnumLiteral)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_EEnumLiteral()
   * @model
   * @generated
   */
  EEnumLiteral getEEnumLiteral();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getEEnumLiteral <em>EEnum Literal</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>EEnum Literal</em>' reference.
   * @see #getEEnumLiteral()
   * @generated
   */
  void setEEnumLiteral(EEnumLiteral value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(EObject)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Target()
   * @model
   * @generated
   */
  EObject getTarget();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(EObject value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mapping.mapping.Operator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.xtext.example.mapping.mapping.Operator
   * @see #setOperator(Operator)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Operator()
   * @model
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.xtext.example.mapping.mapping.Operator
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' attribute.
   * @see #setComment(String)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_Comment()
   * @model
   * @generated
   */
  String getComment();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingRule#getComment <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' attribute.
   * @see #getComment()
   * @generated
   */
  void setComment(String value);

  /**
   * Returns the value of the '<em><b>Child Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mapping.mapping.MappingRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child Rules</em>' containment reference list.
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_ChildRules()
   * @model containment="true"
   * @generated
   */
  EList<MappingRule> getChildRules();

  /**
   * Returns the value of the '<em><b>Child Helpers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mapping.mapping.HelperStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child Helpers</em>' containment reference list.
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingRule_ChildHelpers()
   * @model containment="true"
   * @generated
   */
  EList<HelperStatement> getChildHelpers();

} // MappingRule
