/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingModel#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingModel#getSourceMetamodels <em>Source Metamodels</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingModel#getMainSourceMetamodel <em>Main Source Metamodel</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingModel#getTargetMetamodels <em>Target Metamodels</em>}</li>
 *   <li>{@link org.xtext.example.mapping.mapping.MappingModel#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingModel()
 * @model
 * @generated
 */
public interface MappingModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingModel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Source Metamodels</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mapping.mapping.SourceMetamodel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Metamodels</em>' containment reference list.
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingModel_SourceMetamodels()
   * @model containment="true"
   * @generated
   */
  EList<SourceMetamodel> getSourceMetamodels();

  /**
   * Returns the value of the '<em><b>Main Source Metamodel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main Source Metamodel</em>' reference.
   * @see #setMainSourceMetamodel(SourceMetamodel)
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingModel_MainSourceMetamodel()
   * @model
   * @generated
   */
  SourceMetamodel getMainSourceMetamodel();

  /**
   * Sets the value of the '{@link org.xtext.example.mapping.mapping.MappingModel#getMainSourceMetamodel <em>Main Source Metamodel</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main Source Metamodel</em>' reference.
   * @see #getMainSourceMetamodel()
   * @generated
   */
  void setMainSourceMetamodel(SourceMetamodel value);

  /**
   * Returns the value of the '<em><b>Target Metamodels</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mapping.mapping.TargetMetamodel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Metamodels</em>' containment reference list.
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingModel_TargetMetamodels()
   * @model containment="true"
   * @generated
   */
  EList<TargetMetamodel> getTargetMetamodels();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mapping.mapping.MappingRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.xtext.example.mapping.mapping.MappingPackage#getMappingModel_Rules()
   * @model containment="true"
   * @generated
   */
  EList<MappingRule> getRules();

} // MappingModel
