/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Target Metamodel</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mapping.mapping.MappingPackage#getTargetMetamodel()
 * @model
 * @generated
 */
public interface TargetMetamodel extends Metamodel
{
} // TargetMetamodel
