/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mapping.ui.internal.MappingActivator;

public class MappingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MappingActivator.getInstance().getInjector("org.xtext.example.mapping.Mapping");
	}

}
