/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mapping.mapping.MappingPackage;
import org.xtext.example.mapping.mapping.SourceMetamodel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Source Metamodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SourceMetamodelImpl extends MetamodelImpl implements SourceMetamodel
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SourceMetamodelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MappingPackage.Literals.SOURCE_METAMODEL;
  }

} //SourceMetamodelImpl
