/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mapping.mapping.MappingPackage;
import org.xtext.example.mapping.mapping.TargetMetamodel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Target Metamodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TargetMetamodelImpl extends MetamodelImpl implements TargetMetamodel
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TargetMetamodelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MappingPackage.Literals.TARGET_METAMODEL;
  }

} //TargetMetamodelImpl
