/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MappingStandaloneSetup extends MappingStandaloneSetupGenerated {

	public static void doSetup() {
		new MappingStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
