/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.example.mapping.mapping.HelperStatement;
import org.xtext.example.mapping.mapping.MappingFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Helper Statement</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class HelperStatementTest extends TestCase {

	/**
	 * The fixture for this Helper Statement test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HelperStatement fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(HelperStatementTest.class);
	}

	/**
	 * Constructs a new Helper Statement test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public HelperStatementTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Helper Statement test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(HelperStatement fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Helper Statement test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HelperStatement getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MappingFactory.eINSTANCE.createHelperStatement());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //HelperStatementTest
