/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping.tests;

import junit.textui.TestRunner;

import org.xtext.example.mapping.mapping.MappingFactory;
import org.xtext.example.mapping.mapping.SourceMetamodel;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Source Metamodel</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class SourceMetamodelTest extends MetamodelTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(SourceMetamodelTest.class);
	}

	/**
	 * Constructs a new Source Metamodel test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SourceMetamodelTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Source Metamodel test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected SourceMetamodel getFixture() {
		return (SourceMetamodel)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MappingFactory.eINSTANCE.createSourceMetamodel());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //SourceMetamodelTest
