/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.mapping.tests;

import junit.textui.TestRunner;

import org.xtext.example.mapping.mapping.MappingFactory;
import org.xtext.example.mapping.mapping.TargetMetamodel;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Target Metamodel</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class TargetMetamodelTest extends MetamodelTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(TargetMetamodelTest.class);
	}

	/**
	 * Constructs a new Target Metamodel test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TargetMetamodelTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Target Metamodel test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected TargetMetamodel getFixture() {
		return (TargetMetamodel)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MappingFactory.eINSTANCE.createTargetMetamodel());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //TargetMetamodelTest
