/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.mapping.ui.internal.MappingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MappingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MappingActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MappingActivator activator = MappingActivator.getInstance();
		return activator != null ? activator.getInjector(MappingActivator.ORG_XTEXT_EXAMPLE_MAPPING_MAPPING) : null;
	}

}
