/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mapping.MappingRuntimeModule;
import org.xtext.example.mapping.MappingStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MappingIdeSetup extends MappingStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MappingRuntimeModule(), new MappingIdeModule()));
	}
	
}
