/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mapping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MappingUiModule extends AbstractMappingUiModule {

	public MappingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
